---
title: "dr4pl usage examples"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{dr4pl usage examples}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#packages
```{r}
library(dr4pl)
library(ggplot2)
library(drc)
```

#error cases
```{r}
a <- tryCatch({
  drc::drm(Response~Dose, data = drc_error_1, fct = LL.4())
}, 
warning = function(war) {
  # warning handler picks up where error was generated
  print(paste(war))
},
error = function(err) {
  # error handler picks up where error was generated
  print(paste(err))
})
```

```{r}
a <- dr4pl(Response~Dose, data = drc_error_1, method.robust = "Tukey")
plot(a)
```

```{r}
a <- tryCatch({
  drc::drm(Response~Dose, data = drc_error_2, fct = LL.4())
}, 
warning = function(war) {
  # warning handler picks up where error was generated
  print(paste(war))
},
error = function(err) {
  # error handler picks up where error was generated
  print(paste(err))
})
```

```{r}
a <- dr4pl(Response~Dose, data = drc_error_2, method.init = "Mead", method.robust = "Huber" )
b <- plot(a, breaks.x = c(0.00135, 0.0135, 0.135, 1.35, 13.5) )
b
```
```{r}
a <- tryCatch({
  drc::drm(Response~Dose, data = drc_error_3, fct = LL.4())
}, 
warning = function(war) {
  # warning handler picks up where error was generated
  print(paste(war))
},
error = function(err) {
  # error handler picks up where error was generated
  print(paste(err))
})

```

```{r}
a <- dr4pl(Response~Dose, data = drc_error_3, method.init = "Mead", method.robust = "absolute" )
plot(a, indices.outlier = c(90, 101))
summary(a)

```
```{r}
a <- tryCatch({
  drc::drm(Response~Dose, data = drc_error_4, fct = LL.4())
}, 
warning = function(war) {
  # warning handler picks up where error was generated
  print(paste(war))
},
error = function(err) {
  # error handler picks up where error was generated
  print(paste(err))
})
```

```{r}
a <- dr4pl(Response~Dose, data = drc_error_4, method.init = "Mead", method.robust = "absolute" )
plot(a)
```

```{r}
a <- dr4pl(Response~Dose, data = sample_data_1,  method.init = "Mead")
plot(a)
```

```{r}
a <- dr4pl(Response~Dose, data = sample_data_2,  method.init = "Mead")
plot(a)
summary(a)
```

```{r}
a <- dr4pl(Response~Dose, data = sample_data_3, method.init = "Mead")
plot(a)
```

```{r}
a <- dr4pl(Response~Dose, data = sample_data_4, method.init = "Mead")
plot(a)
```

```{r}
a <- dr4pl(Response~Dose, data = sample_data_5, method.init = "Mead")
plot(a)
```

```{r}
a <- dr4pl(Response~Dose, data = sample_data_6, method.init = "Mead", method.robust = "absolute")
plot(a)
```

```{r}
a <- dr4pl(Response~Dose, data = sample_data_6, method.init = "Mead", method.robust = "absolute")
plot(a)
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

