#' @name DR4PL
#' @docType package
#' @title Dose response data analysis using the 4 Parameter Logistic model
#' @description Main functions related to fitting
#' @author Hyowon An, Lineberger Comprehensive Cancer Center
#' @details Last updated: 09/19/2016
#' @import stats
#' @import graphics
#' @import ggplot2

#' @param constrained Boolean for whether or not this function is constrained.
#' @param grad Gradient function
#' @param init.parm Vector of initial parameters
#' @param method.init Initialization method
#' @param method.optim Optimization method
#' @param method.robust Robust estimation method
#'      - NULL: Sum of squares loss
#'      - absolute: Absolute deviation loss
#'      - Huber: Huber's loss
#'      - Tukey: Tukey's biweight loss
#' @param trace Nonnegative number indicating the level of detailedness of output
#'   generated by \code{optim}. As its value increases, more detailed output is
#'   printed.
drraEst <- function(dose, response,
                    constrained = constrained,
                    grad,
                    init.parm,
                    method.init,
                    method.optim,
                    method.robust,
                    trace = 0) {

  x <- dose  # Vector of dose values
  y <- response  # Vector of responses

  # Choose the loss function depending on the robust estimation method
  err.fcn <- ErrFcn(method.robust)

  if(!is.null(init.parm)) {  # When initial parameter estimates are given

    theta.init <- init.parm

    # Fit a dose-response model
    drr <- optim(par = theta.init,
                 fn = err.fcn,
                 gr = grad,
                 method = method.optim,
                 x = x,
                 y = y,
                 control = list(trace = trace))

    theta <- drr$par
    error <- drr$value

  } else {  # When initial parameter values are not given

    # Set initial values of parameters
    theta.init <- FindInitialParms(x, y, method.init, method.robust)

    names(theta.init) <- c("Upper limit", "IC50", "Slope", "Lower limit")

    # drr <- optim(par = theta.init,
    #              fn = err.fcn,
    #              gr = grad,
    #              method = method.optim,
    #              x = x,
    #              y = y,
    #              control = list(trace = trace))

    constr.matr <- matrix(c(0, 1, 0, 0), nrow = 1, ncol = 4)
    constr.vec <- 0

    drr <- constrOptim(theta = theta.init,
                       f = err.fcn,
                       grad = grad,
                       ui = constr.matr,
                       ci = constr.vec,
                       method = method.optim,
                       x = x,
                       y = y)

    theta <- drr$par
    error <- drr$value
  }

  data.drr <- data.frame(Dose = dose, Response = response)

  convergence <- TRUE

  list(convergence = convergence,
       data = data.drr,
       dose = x,
       response = y,
       parameters = theta,
       error.value = error)
}

#' @description Fit the 4 parameter logistic model to the data using the function `DR4PLEst'
#' @param x Object to DR4PL.
#' @param ... arguments passed to coef
#' @export
drra <- function(x, ...) UseMethod("drra")

#' @describeIn DR4PL Used in the default case, supplying a single dose and response variable
#' @param dose Dose
#' @param response Response
#' @export
drra.default <- function(dose, response,
                         constrained = FALSE,
                         grad = NULL,
                         init.parm = NULL,
                         method.init = "logistic",
                         method.optim = if(is.null(grad)) "Nelder-Mead" else "BFGS",
                         method.robust = NULL,
                         trace = 0,
                         ...) {

  ### If doses and responses are not numeric, then throw.
  # if(class(dose) != "numeric" || class(response) != "numeric") {
  #   stop("Both doses and responses should be given numeric values.")
  # }

  dose <- as.numeric(dose)
  response <- as.numeric(response)

  drra.obj <- drraEst(dose = dose, response = response,
                      constrained = constrained,
                      grad = grad,
                      init.parm = init.parm,
                      method.init = method.init,
                      method.optim = method.optim,
                      method.robust = method.robust,
                      trace = trace)

  drra.obj$call <- match.call()

  class(drra.obj) <- "drra"
  return(drra.obj)
}

#' @title Fit a 4 parameter logistic (4PL) model to dose-response data.
#'
#' @description A general 4PL model fitting function for analysis of
#'   dose-response relation.
#'
#' @param  formula A symbolic description of the model to be fit. Either of the
#'   form 'response ~ dose' or as a data frame with response values in first
#'   column and dose values in second column.
#' @param constrained Boolean for whether or not this function is constrained.
#' @param data A data frame containing variables in the model.
#' @param grad A function returning the gradient values for the optimization
#'   methods "BFGS", "CG" and "L-BFGS-B". If it is NULL, the Nelder-Mead method
#'   will be applied.
#' @param init.parm A vector of initial parameters to be optimized in the model.
#' @param method.init The method of obtaining initial values of the parameters.
#'   If it is NULL, a default "logistic" regression method will be used.
#' @param method.optim The method of optimization of the parameters. This method
#'   name is directly applied to the \code{constrOptim} function provided in the
#'   "base" package of R.
#' @param method.robust The robust estimation method to be used to fit a model.
#'   If it is NULL, then the default least sum of squares estimator is used.
#' @param trace Nonnegative number indicating the level of detailedness of output
#'   generated by \code{optim}. As its value increases, more detailed output is
#'   printed.
#' @param ... Further arguments to be passed to \code{constrOptim}.
#' @return A 'DR4PL' object for which "confint", "gof", "print" and "summary"
#'   methods are implemented. For details, see the help page of each method.
#'   For example, type \code{?confint.DR4PL} to obtain the confidence intervals
#'   of parameters of the 'DR4PL' object.
#' @details This function fits a 4 parameter logistic (4PL) model to dose-response
#'   data. A formula of the model is
#'   \deqn{\theta[1]+(\theta[4]-\theta[1])/(1+(x/\theta[2])^\theta[3])}
#'
#'   \code{method.init} specifies an initialization method to get initial parameter
#'   estimates based on data. The currently supported initialization methods are
#'   "Logistic", "Mead", "Anke". Details of the methods are given in Section
#'   "Details".
#'
#'   \code{method.optim} specifies an optimization method to be used in
#'   "constrOptim" function. The currently supported optimization techniques
#'   include "Nelder-Mead", "BFGS", "CG", "L-BFGS-B", "SANN" and "Brent". For
#'   further details, see the help page of \code{\link[stats]{optim}}.
#'
#'   \code{method.robust} chooses a robust estimation method among 4 methods.
#'   The method of estimation is usually identified by the loss function of the
#'   method. This package implements 4 loss functions: sum of squares loss,
#'   absolute deviation loss, Huber's loss and Tukey's biweight loss. Each of
#'   loss function is explained in detail in the vignette.
#' @author Hyowon An, J. S. Marron and Dirk P. Dittmer
#' @seealso \code{\link{print.DR4PL}}
#' @examples
#' ryegrass.DR4PL <- DR4PL(Response ~ Dose, data = sample_data1)
#'
#' ryegrass.DR4PL
#' @author Hyowon An, Dirk P. Dittmer and J. S. Marron
#' @seealso \code{\link{confint.DR4PL}}, \code{\link{gof.DR4PL}},
#' \code{\link{print.DR4PL}}, \code{\link{summary.DR4PL}}
#' @export
drra.formula <- function(formula,
                         constrained = FALSE,
                         data = list(),
                         grad = NULL,
                         init.parm = NULL,
                         method.init = "logistic",
                         method.optim = if(is.null(grad)) "Nelder-Mead" else "BFGS",
                         method.robust = NULL,
                         trace = 0,
                         ...) {

  mf <- model.frame(formula = formula, data = data)
  dose <- model.matrix(attr(mf, "terms"), data = mf)[, 2]
  response <- model.response(mf)

  est <- drra.default(dose = dose, response = response,
                      constrained = constrained,
                      grad = grad,
                      init.parm = init.parm,
                      method.init = method.init,
                      method.optim = method.optim,
                      method.robust = method.robust,
                      trace = trace,
                      ...)

  est$call <- match.call()
  est$formula <- formula
  names(est$parameters) <- c("Upper limit", "IC50", "Slope", "Lower limit")
  
  return(est)
}

#' @description Coefficient of a `DR4PL' object
#' @title coef
#' @name coef.DR4PL
#' @param object A 'DR4PL' object
#' @param ... arguments passed to coef
#
#' @return A vector of parameters
#' @export
coef.drra <- function(object, ...) {
  
  object$parameters
}

#' @description A default plotting function for a `DR4PL' object.
#' @title plot
#' @name plot.DR4PL
#' @param object A `DR4PL' object whose mean response function should be plotted.
#' @param ... All arguments that can normally be passed to plot.
#' @examples
#' ryegrass.DR4PL <- DR4PL::DR4PL(Response ~ Dose, data = sample_data_1)
#'
#' plot(ryegrass.DR4PL)
#' @export
plot.drra <- function(object, ...) {

  a <- ggplot2::ggplot(aes(x = object$data$Dose, y = object$data$Response), data = object$data)

  a <- a + ggplot2::stat_function(fun = MeanResponse,
                         args = list(theta = object$parameters),
                         size = 1.2)

  a <- a + ggplot2::geom_point(size = I(5), alpha = I(0.8), color = "blue")

  a <- a + ggplot2::labs(title = "Dose response curve",
                         x = "Dose",
                         y = "Response")
  

  # Set parameters for the grids
  a <- a + ggplot2::theme(strip.text.x = ggplot2::element_text(size = 16))
  a <- a + ggplot2::theme(panel.grid.minor = ggplot2::element_blank())
  a <- a + ggplot2::theme(panel.grid.major = ggplot2::element_blank())
  a <- a + ggplot2::scale_x_log10()
  a <- a + ggplot2::theme_bw()
  
  # Set parameters for the titles and text / margin(top, right, bottom, left)
  a <- a + ggplot2::theme(plot.title = ggplot2::element_text(size = 20, margin = ggplot2::margin(0, 0, 10, 0)))
  a <- a + ggplot2::theme(axis.title.x = ggplot2::element_text(size = 16, margin = ggplot2::margin(15, 0, 0, 0)))
  a <- a + ggplot2::theme(axis.title.y = ggplot2::element_text(size = 16, margin = ggplot2::margin(0, 15, 0, 0)))
  a <- a + ggplot2::theme(axis.text.x = ggplot2::element_text(size = 16))
  a <- a + ggplot2::theme(axis.text.y = ggplot2::element_text(size = 16))

  return(a)
}

#' Print the DR4PL object to screen.
#'
#' @param object a DR4PL object to be printed
#' @param ... all normally printable arguments
#' @examples
#' ryegrass.DR4PL <- DR4PL(Response ~ Dose,
#'                       data = sample_data_1)
#'
#' print(ryegrass.DR4PL)
print.drra <- function(object, ...) {
  
  cat("Call:\n")
  print(object$call)

  cat("\nCoefficients:\n")
  print(object$parameters)
}

#' Print the drra object summary to screen.
#' @param object a DR4PL object to be summarized
#' @param ... all normally printable arguments
print.summary.drra <- function(object, ...) {
  
  cat("Call:\n")
  print(object$call)
  cat("\n")

  printCoefmat(object$coefficients, P.value = TRUE, has.Pvalue = TRUE)
}

#' Print the DR4PL object summary.
#' @param object a DR4PL object to be summarized
#' @param ... all normal summary arguments
#' @export
summary.drra <- function(object, ...) {

  TAB <- cbind(Estimate = object$parameters,
               StdErr = object$std.err,
               t.value = object$t.value,
               p.value = object$p.value)

  res <- list(call = object$call,
              coefficients = TAB)

  class(res) <- "summary.DR4PL"
  res
}


#' These are a handful of experimentally derived datasets from the wet-laboratory.
#' These all have numerical errors in other dose-response curve-packages, but not using these methods.
#' @title sample_data_1
#' @name sample_data_1
#' @docType data
#' @keywords sample_data
NULL
#' These are a handful of experimentally derived datasets from the wet-laboratory.
#' These all have numerical errors in other dose-response curve-packages, but not using these methods.
#' @title sample_data_2
#' @name sample_data_2
#' @docType data
#' @keywords sample_data
NULL
#' These are a handful of experimentally derived datasets from the wet-laboratory.
#' These all have numerical errors in other dose-response curve-packages, but not using these methods.
#' @title sample_data_3
#' @name sample_data_3
#' @docType data
#' @keywords sample_data
NULL
#' These are a handful of experimentally derived datasets from the wet-laboratory.
#' These all have numerical errors in other dose-response curve-packages, but not using these methods.
#' @title sample_data_4
#' @name sample_data_4
#' @docType data
#' @keywords sample_data
NULL
#' These are a handful of experimentally derived datasets from the wet-laboratory.
#' These all have numerical errors in other dose-response curve-packages, but not using these methods.
#' @title sample_data_5
#' @name sample_data_5
#' @docType data
#' @keywords sample_data
NULL
#' These are a handful of experimentally derived datasets from the wet-laboratory.
#' These all have numerical errors in other dose-response curve-packages, but not using these methods.
#' @title sample_data_6
#' @name sample_data_6
#' @docType data
#' @keywords sample_data
NULL
#' These are a handful of experimentally derived datasets from the wet-laboratory.
#' These all have numerical errors in other dose-response curve-packages, but not using these methods.
#' @title sample_data_7
#' @name sample_data_7
#' @docType data
#' @keywords sample_data
NULL
#' These are a handful of experimentally derived datasets from the wet-laboratory.
#' These all have numerical errors in other dose-response curve-packages, but not using these methods.
#' @title sample_data_8
#' @name sample_data_8
#' @docType data
#' @keywords sample_data
NULL
#' These are a handful of experimentally derived datasets from the wet-laboratory.
#' These all have numerical errors in other dose-response curve-packages, but not using these methods.
#' @title sample_data_9
#' @name sample_data_9
#' @docType data
#' @keywords sample_data
NULL
#' These are a handful of experimentally derived datasets from the wet-laboratory.
#' These all have numerical errors in other dose-response curve-packages, but not using these methods.
#' @title sample_data_10
#' @name sample_data_10
#' @docType data
#' @keywords sample_data
NULL
#' These are a handful of experimentally derived datasets from the wet-laboratory.
#' These all have numerical errors in other dose-response curve-packages, but not using these methods.
#' @title sample_data_11
#' @name sample_data_11
#' @docType data
#' @keywords sample_data
NULL
#' These are a handful of experimentally derived datasets from the wet-laboratory.
#' These all have numerical errors in other dose-response curve-packages, but not using these methods.
#' @title sample_data_12
#' @name sample_data_12
#' @docType data
#' @keywords sample_data
NULL
#' These are a handful of experimentally derived datasets from the wet-laboratory.
#' These all have numerical errors in other dose-response curve-packages, but not using these methods.
#' @title sample_data_13
#' @name sample_data_13
#' @docType data
#' @keywords sample_data
NULL
#' These are a handful of experimentally derived datasets from the wet-laboratory.
#' These all have numerical errors in other dose-response curve-packages, but not using these methods.
#' @title Single High Outlier
#' @name drc_error_1
#' @docType data
#' @keywords sample_data
NULL
#' These are a handful of experimentally derived datasets from the wet-laboratory.
#' These all have numerical errors in other dose-response curve-packages, but not using these methods.
#' @title Multiple High Outliers at Different measurements 
#' @name drc_error_2
#' @docType data
#' @keywords sample_data
NULL
#' These are a handful of experimentally derived datasets from the wet-laboratory.
#' These all have numerical errors in other dose-response curve-packages, but not using these methods.
#' @title Support Problem and Outliers at a Single Dose Level
#' @name drc_error_3
#' @docType data
#' @keywords sample_data
NULL
#' These are a handful of experimentally derived datasets from the wet-laboratory.
#' These all have numerical errors in other dose-response curve-packages, but not using these methods.
#' @title Support Problem
#' @name drc_error_4
#' @docType data
#' @keywords sample_data
NULL